/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#364d1c',
        'charcoal-text': '#1A1A1A',
        'matcha-bg': '#BAD797',
        background: '#fcf9f8',
        'cherry-accent': '#670626',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'on-surface-variant': '#44483d',
        'on-tertiary-container': '#4d5b4e',
        'inverse-primary': '#b3d091',
        tertiary: '#546255',
        'on-background': '#1c1b1b',
        'on-primary-container': '#465e2b',
        secondary: '#a33851',
        'surface-dim': '#dcd9d9',
        'on-secondary-fixed': '#400013',
        'error-container': '#ffdad6',
        'surface-container-low': '#f6f3f2',
        'secondary-fixed-dim': '#ffb2bd',
        'surface-container-highest': '#e5e2e1',
        'on-tertiary-fixed': '#121e14',
        'on-tertiary': '#ffffff',
        surface: '#fcf9f8',
        'primary-container': '#bad797',
        'on-secondary-fixed-variant': '#84203a',
        'tertiary-fixed-dim': '#bbcbbb',
        'primary-fixed-dim': '#b3d091',
        'outline-variant': '#c4c8ba',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#74132f',
        'tertiary-container': '#c3d2c2',
        'primary-fixed': '#cfecaa',
        'surface-variant': '#e5e2e1',
        'on-primary-fixed': '#0f2000',
        'surface-tint': '#4d6631',
        'on-primary': '#ffffff',
        'tertiary-fixed': '#d7e7d6',
        'secondary-fixed': '#ffd9dd',
        'surface-container-high': '#eae7e7',
        'on-surface': '#1c1b1b',
        primary: '#4d6631',
        'on-secondary': '#ffffff',
        'on-tertiary-fixed-variant': '#3d4a3e',
        'surface-container': '#f0eded',
        outline: '#75796c',
        'surface-bright': '#fcf9f8',
        'secondary-container': '#fd7e96',
        'cream-surface': '#F8F7F2',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f0ef',
        'warm-white': '#FAFAF8',
        'deep-forest': '#243126',
        'ink-black': '#121214',
        'deep-cabernet': '#4A1521',
        'champagne-silk': '#F3ECE0',
        'on-error': '#ffffff',
        // Inka AI brand colors
        'primary-blue': '#2563EB',
        'primary-hover-blue': '#1D4ED8',
        'dark-navy': '#0F172A',
        'slate': '#1E293B',
        'soft-blue': '#DBEAFE',
        'off-white': '#F8FAFC',
        'light-gray': '#F1F5F9',
        'border-gray': '#CBD5E1',
        'body-text': '#475569',
        'muted-text': '#64748B',
        'success-accent': '#10B981',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-desktop': '64px',
        'container-max': '1440px',
        unit: '8px',
        'margin-mobile': '20px',
        gutter: '32px',
        'section-gap': '160px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'display-lg': ['"EB Garamond"', 'serif'],
        button: ['"Hanken Grotesk"', 'sans-serif'],
        'headline-lg': ['"EB Garamond"', 'serif'],
        'display-lg-mobile': ['"EB Garamond"', 'serif'],
        'label-caps': ['"Hanken Grotesk"', 'sans-serif'],
        'headline-md': ['"EB Garamond"', 'serif'],
        'body-md': ['"Hanken Grotesk"', 'sans-serif'],
        'body-lg': ['"Hanken Grotesk"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['96px', { lineHeight: '100%', letterSpacing: '-0.04em', fontWeight: '400' }],
        button: ['14px', { lineHeight: '100%', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg': ['64px', { lineHeight: '110%', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg-mobile': ['48px', { lineHeight: '110%', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-lg-mobile': ['48px', { lineHeight: '110%', letterSpacing: '-0.02em', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '140%', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-md': ['40px', { lineHeight: '120%', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '160%', fontWeight: '400' }],
        'body-lg': ['20px', { lineHeight: '160%', fontWeight: '400' }],
      },
      transitionDuration: {
        400: '400ms',
        600: '600ms',
      },
    },
  },
  plugins: [],
};
